name: checkPHP

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PHP Syntax Checker (Lint)
        uses: StephaneBour/actions-php-lint@8.1
        with:
          dir: '.'
